### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sokkanen** [Darake/ruokaholvi#1]
.zip ladattu maanantaina 25.2.2019 klo 09:30

#### Lähdekoodi ja asentaminen
* Ohjelma lähti toimimaan paikallisesti ohjeiden mukaisesti, joskin ohjeisiin oli jäänyt yksi ylimääräinen merkki, joka aiheutti ensin virheen:
```
”& export DATABASE_URL="oma_postgresql_tietokanta_tähän"”
```
Tästä piti jättää pois merkki ”&”. 
* Lähdekoodi on erittäin selkeää ja melkein itsensä dokumentoivaa. Toki joissakin kohdissa kommentit olisivat voineet tehdä koodista paremmin sisäistettävää.
* Opin itsekin paljon uutta. Erityisesti tiedostojen käsittely (kuvan lataaminen) oli itselle uutta Python-ympäristössä.

#### Toimivuus ja käytettävyys
* Kaikki ohjelman ominaisuudet toimivat, syötteet validoidaan ja käyttöliittymä on selkeä.
  * Ainesosien toiminnallisuudet toimivat ja käyttäminen on intuitiivista
  * Reseptien lisääminen onnistui hienosti.
* Ohjelman käyttöliittymän ulkoasu on erittäin hieno! Erityismaininta todella tyylikkäästä reseptilistauksesta kuvineen.

#### Muuta
* Voisiko asennusohjeen laittaa erilliseksi tiedostoksi, jolloin README pysyisi hieman selkeämpänä? Tämä on toki puhtaasti makuasia.

Kokonaisuutena erittäin hieno projekti. Loistotyötä!

**Comment by Darake** [comment]
Kiitos paljon palautteesta ja kehuista! Korjasin tuon typon asennusohjeista ja siirsin erilliseen tiedostoon asennus- sekä käyttöohjeet.
