### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sebazai** [Darake/ruokaholvi#2]
Koodi ladattu 25.2.2019 klo. 10.25

Hienolta näyttää sivusto ja ulkoasu on todella selkeä ja komea.
Selkeät asennusohjeet ja sain asennettua omalle koneelleni todella helposti, jolloin pääsin admin puolelle katsomaan toiminnallisuuksia. Todella hienosti toimi myös paikallisesti PostgreSQL:llä. Asennusohjeissa olisi hyvä olla myös miten se siirretään tuotantoon, eli esimerkiksi Herokuun.

Hyvin olet saanut tehtyä sivustoa ja toiminnallisuuksia lisättyä, ostoslista ja ruokahävikkiä toiminnallisuutta en löytänyt, mutta olet selvästi rakentanut tietokantaa siihen suuntaan. Todella hyvää työtä, alla omia esille tulleita asioita.

**Koodista ja tietokannasta**
Koodissa on username unique metodi, joka tarkistaa onko käyttäjätunnus uniikki, mutta tietokannassa username kenttää ei ole määrätty uniikiksi, tämän tarkistuksen voisi tehdä myös backendissä/tietokannassa.

Lomakkeiden validointi puuttuu, jos nyt lisään johonkin lomakkeeseen yli 144 merkkiä pitkän tekstin, niin sovellus kaatuu. Olet hienosti tehnyt omia validointeja, mutta esim pituutta tekstikentistä ei tällä hetkellä validoida.

Onko jokin syy, miksi ingredient sarake "amount" on tekstikenttä eikä integer? Nyt kun lisään reseptiä, voin lisätä määrä kenttään tekstiä.

Koodi on selkeä ja johdonmukainen muuten. Selkeästi nimetty metodit ja muuttujat.

**Dokumentaatio ja käytettävyys**

Kun painaa raaka-ainetta, niin se näyttää reseptit mihin tätä raaka-ainetta voi käyttää, tätä ei ole käyttöohjeissa mainittu ja käyttäjä ei välttämättä tajua painaa omaa raaka-ainetta, jotta näkisi reseptit mihin voi käyttää kyseistä raaka-aineta.

Selkeyden vuoksi käyttöohjeet ja asennusohjeet voisivat olla omassa .md tiedostossa documentation kansiossa ja README.md tiedostossa ainoastaan linkit tiedostoihin.

User storeissa olisi tarpeena olla vielä SQL kyselyt tapahtumista, jolloin olisi nämäkin dokumentoitu.

**Pieniä huomautuksia**

- templates/auth/loginform.html, niin div tägi:  div class="form-group" on sulkematta. Olisi myös ehkä hyvä laittaa tuo "Register" painike form tägien sisään
- templates/auth/registrationform.html, niin username div tägi on myös sulkematta.
- Tietokantakuvasta puuttuu "recipe" taulusta (fk) account_id

**Comment by Darake** [comment]
Kiitos paljon palautteesta. Korjailin noita lomakkeiden validointeja nyt kun oli aikaa. Suljin myös div tagit.
Amount on tarkoituksella tekstikenttä, jotta käyttäjä voi laittaa vähän vapaaluontoisemmin siihen arvoja. Esim. 150g tai 2kpl jne. Toki tästä voi koitua hankaluuksia, jos joskus lisään ruokahävikki toiminnallisuuden.
